// Generated by   : ImageConverter 565 Online
// Generated from : multicolor-designify.png
// Time generated : Sat, 12 Nov 22 15:45:56 +0100  (Server timezone: CET)
// Image Size     : 320x480 pixels
// Memory usage   : 307200 bytes


#if defined(__AVR__)
    #include <avr/pgmspace.h>
#elif defined(__PIC32MX__)
    #define PROGMEM
#elif defined(__arm__)
    #define PROGMEM
#endif
